name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Python (if not already installed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@main
        with:
            credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


      # Deploy to Google Cloud App Engine
      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet
