name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@main
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/ingka-ilo-cybersecurity-dev/my-python-app
          service_account_email: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          region: us-central1
          platform: managed
          allow-unauthenticated: true # Set to false for authentication required

      # Optionally, you can add more steps for testing, linting, etc.
