name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Python (if not already installed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Deploy to Google Cloud App Engine
      - name: Deploy to App Engine
        env:
            PROJECT_ID: ingka-ilo-cybersecurity-dev
            credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        run: |
            echo "$credentials_json" | gcloud auth activate-service-account --key-file=- --project=$PROJECT_ID
            gcloud app deploy app.yaml --quiet
